version: "3"
services:
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
